### ISSUE TITLE
Problema al agregar URL de notificación

### ISSUE THREAD

**Issue by FedeM** [mercadopago/DEPRECATED-sdk-php#74]
Buenos días. Estoy tratando de hacer un Checkout básico, uso el código de la documentación para ello. El problema viene cuando quiero agregar la URL a "[Recibe notificaciones de pagos](https://www.mercadopago.com.ar/ipn-notifications/save)" y recibo el siguiente error: **La URL ingresada no responde un HTTP status correcto. Debe responder 200 o 201.**

En el servidor estoy recibiendo este mensaje se error: 

`[10-Nov-2016 08:10:34 America/Chicago] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[10-Nov-2016 08:10:34 America/Chicago] PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'Problem with the SSL CA cert (path? access rights?)' in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php:509
Stack trace:
#0 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(558): MPRestClient::exec(Array)
#1 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(67): MPRestClient::post(Array)
#2 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(329): MP->get_access_token()
#3 /public_html/test_mp/receive-ipn.php(24): MP->get('/collections/no...')
#4 {main}
  thrown in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php on line 509
[10-Nov-2016 08:10:34 America/Chicago] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[10-Nov-2016 08:10:34 America/Chicago] PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'Problem with the SSL CA cert (path? access rights?)' in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php:509
Stack trace:
#0 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(558): MPRestClient::exec(Array)
#1 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(67): MPRestClient::post(Array)
#2 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(329): MP->get_access_token()
#3 /public_html/test_mp/receive-ipn.php(24): MP->get('/collections/no...')
#4 {main}
  thrown in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php on line 509
[10-Nov-2016 08:10:35 America/Chicago] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[10-Nov-2016 08:10:35 America/Chicago] PHP Fatal error:  Uncaught exception 'MercadoPagoException' with message 'Problem with the SSL CA cert (path? access rights?)' in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php:509
Stack trace:
#0 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(558): MPRestClient::exec(Array)
#1 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(67): MPRestClient::post(Array)
#2 /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php(329): MP->get_access_token()
#3 /public_html/test_mp/receive-ipn.php(24): MP->get('/collections/no...')
#4 {main}
  thrown in /public_html/test_mp/vendor/mercadopago/sdk/lib/mercadopago.php on line 509`

¿A qué se puede deber el error? Estuve leyendo que el error de $HTTP_RAW_POST_DATA se soluciona desde el archivo php.ini pero mi servidor no permite editarlo.

¿Cómo podría solucionarlo?

Desde ya, muchas gracias.

**Comment by tesoner** [comment]
Hermano el problema que tienes es que hay un error en el código, por tanto al acceder a la url se obtiene un error 500 en vez de un 200.

1. Asegurate de que tu respuesta sea: 
 ```
header("HTTP/1.1 200 OK");
return \Response::json(['HTTP/1.1 200 OK'], 200);
```
2. Soluciona los errores en tu código.

**Comment by FedeM** [comment]
El problema lo solucioné de otra forma, terminé armando un cronjob y aparentemente el error es porque el servidor no soporta las funciones requeridas por la API.
